# ==========================================
# HIKOO BACKEND
# ==========================================

spring.application.name=hikoo-backend

# ==========================================
# SERVER
# ==========================================

server.port=8080


# ==========================================
# POSTGRESQL DATABASE
# ==========================================

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/hikoo_db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:Hikoo1@2}

spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# JWT
# ==========================================

# JWT
app.jwt.secret=HIKOO_BACKEND_JWT_SECRET_CHANGE_THIS_TO_A_LONG_RANDOM_VALUE_2026
app.jwt.expiration=86400000

#super admin
app.super-admin.name=HIKOO Super Admin
app.super-admin.email=superadmin@hikoo.com
app.super-admin.password=SuperAdmin@123
